// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type socketFlowFlowEvent struct {
	_           structs.HostLayout
	MonotonicNs uint64
	CgroupId    uint64
	Pid         uint32
	Family      uint8
	Protocol    uint8
	State       uint8
	Pad1        uint8
	LocalPort   uint16
	RemotePort  uint16
	LocalAddr   [16]uint8
	RemoteAddr  [16]uint8
	Pad2        uint32
	Sent        uint64
	Received    uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	socketFlowMapEvents                 = "events"
	socketFlowMapPendingSends           = "pending_sends"
	socketFlowMapUdpReceives            = "udp_receives"
	socketFlowProgTraceTcpCleanupRbuf   = "trace_tcp_cleanup_rbuf"
	socketFlowProgTraceTcpSendmsg       = "trace_tcp_sendmsg"
	socketFlowProgTraceTcpSendmsgReturn = "trace_tcp_sendmsg_return"
	socketFlowProgTraceUdpRecvmsg       = "trace_udp_recvmsg"
	socketFlowProgTraceUdpRecvmsgReturn = "trace_udp_recvmsg_return"
	socketFlowProgTraceUdpSendmsg       = "trace_udp_sendmsg"
	socketFlowProgTraceUdpSendmsgReturn = "trace_udp_sendmsg_return"
)

// loadSocketFlow returns the embedded CollectionSpec for socketFlow.
func loadSocketFlow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SocketFlowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load socketFlow: %w", err)
	}

	return spec, err
}

// loadSocketFlowObjects loads socketFlow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*socketFlowObjects
//	*socketFlowPrograms
//	*socketFlowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSocketFlowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSocketFlow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// socketFlowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketFlowSpecs struct {
	socketFlowProgramSpecs
	socketFlowMapSpecs
	socketFlowVariableSpecs
}

// socketFlowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketFlowProgramSpecs struct {
	TraceTcpCleanupRbuf   *ebpf.ProgramSpec `ebpf:"trace_tcp_cleanup_rbuf"`
	TraceTcpSendmsg       *ebpf.ProgramSpec `ebpf:"trace_tcp_sendmsg"`
	TraceTcpSendmsgReturn *ebpf.ProgramSpec `ebpf:"trace_tcp_sendmsg_return"`
	TraceUdpRecvmsg       *ebpf.ProgramSpec `ebpf:"trace_udp_recvmsg"`
	TraceUdpRecvmsgReturn *ebpf.ProgramSpec `ebpf:"trace_udp_recvmsg_return"`
	TraceUdpSendmsg       *ebpf.ProgramSpec `ebpf:"trace_udp_sendmsg"`
	TraceUdpSendmsgReturn *ebpf.ProgramSpec `ebpf:"trace_udp_sendmsg_return"`
}

// socketFlowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketFlowMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	PendingSends *ebpf.MapSpec `ebpf:"pending_sends"`
	UdpReceives  *ebpf.MapSpec `ebpf:"udp_receives"`
}

// socketFlowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketFlowVariableSpecs struct {
}

// socketFlowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSocketFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketFlowObjects struct {
	socketFlowPrograms
	socketFlowMaps
	socketFlowVariables
}

func (o *socketFlowObjects) Close() error {
	return _SocketFlowClose(
		&o.socketFlowPrograms,
		&o.socketFlowMaps,
	)
}

// socketFlowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSocketFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketFlowMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	PendingSends *ebpf.Map `ebpf:"pending_sends"`
	UdpReceives  *ebpf.Map `ebpf:"udp_receives"`
}

func (m *socketFlowMaps) Close() error {
	return _SocketFlowClose(
		m.Events,
		m.PendingSends,
		m.UdpReceives,
	)
}

// socketFlowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSocketFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketFlowVariables struct {
}

// socketFlowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSocketFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketFlowPrograms struct {
	TraceTcpCleanupRbuf   *ebpf.Program `ebpf:"trace_tcp_cleanup_rbuf"`
	TraceTcpSendmsg       *ebpf.Program `ebpf:"trace_tcp_sendmsg"`
	TraceTcpSendmsgReturn *ebpf.Program `ebpf:"trace_tcp_sendmsg_return"`
	TraceUdpRecvmsg       *ebpf.Program `ebpf:"trace_udp_recvmsg"`
	TraceUdpRecvmsgReturn *ebpf.Program `ebpf:"trace_udp_recvmsg_return"`
	TraceUdpSendmsg       *ebpf.Program `ebpf:"trace_udp_sendmsg"`
	TraceUdpSendmsgReturn *ebpf.Program `ebpf:"trace_udp_sendmsg_return"`
}

func (p *socketFlowPrograms) Close() error {
	return _SocketFlowClose(
		p.TraceTcpCleanupRbuf,
		p.TraceTcpSendmsg,
		p.TraceTcpSendmsgReturn,
		p.TraceUdpRecvmsg,
		p.TraceUdpRecvmsgReturn,
		p.TraceUdpSendmsg,
		p.TraceUdpSendmsgReturn,
	)
}

func _SocketFlowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed socketflow_bpfel.o
var _SocketFlowBytes []byte
